version: "3.7"
services:

  jenkins:
    image: jenkins/jenkins-maven:latest
    build: ./jenkins/
    deploy:
      replicas: 1
    healthcheck:
      test: "exit 0"
    ports:
      - "7070:8080"
      - "50003:50000"
    networks:
      - cicd-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube
    ports:
      - "7000:9000"
    networks:
      - cicd-net
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar

  db:
    image: postgres
    networks:
      - cicd-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  nexus:
    image: sonatype/nexus
    networks:
      - cicd-net
    ports:
      - "7081:8081"

networks:
  cicd-net:
    driver: bridge
