version: "3.7"
services:

  jenkins:
    image: jenkins/jenkins-maven:latest
    build: ./jenkins/
    deploy:
      replicas: 1
    healthcheck:
      test: "exit 0"
    ports:
      - "7070:8080"
      - "50003:50000"
    networks:
      - cicd-net
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube
    ports:
      - "7000:9000"
    networks:
      - cicd-net
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar

    volumes:
      - ./sonarqube/data/conf:/opt/sonarqube/conf
      - ./sonarqube/data/data:/opt/sonarqube/data
      - ./sonarqube/data/extensions:/opt/sonarqube/extensions
      - ./sonarqube/data/bundled_plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - cicd-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./postgresql/data/data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus
    networks:
      - cicd-net
    volumes:
      - ./nexus/data:/sonatype-work
    ports:
      - "7081:8081"

networks:
  cicd-net:
    driver: overlay
